name: h1bdata
channels:
  - defaults
  - conda-forge
dependencies:
  - asn1crypto=0.24.0=py36_0
  - beautifulsoup4=4.7.1=py36_1
  - blas=1.0=mkl
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py36_0
  - cffi=1.12.2=py36hb5b8e2f_1
  - chardet=3.0.4=py36_1
  - cryptography=2.6.1=py36ha12b0ac_0
  - cython=0.28.2=py36h1de35cc_0
  - html5lib=1.0.1=py36_0
  - icu=58.2=h4b95b61_1
  - idna=2.6=py36h8628d0a_1
  - intel-openmp=2019.3=199
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libxml2=2.9.9=hab757c2_0
  - libxslt=1.1.33=h33a18ac_0
  - lxml=4.2.1=py36h7166777_0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py36hb8a8100_0
  - mkl_random=1.0.1=py36h5d10147_1
  - ncurses=6.1=h0a44026_1
  - numpy=1.14.3=py36h9bb19eb_1
  - numpy-base=1.14.3=py36h479e554_1
  - openssl=1.1.1b=h1de35cc_1
  - pandas=0.23.0=py36h1702cab_0
  - pip=19.0.3=py36_0
  - pycparser=2.19=py36_0
  - pyopenssl=19.0.0=py36_0
  - pysocks=1.6.8=py36_0
  - python=3.6.8=haf84260_0
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.4=py36_0
  - readline=7.0=h1de35cc_5
  - requests=2.21.0=py36_0
  - setuptools=41.0.0=py36_0
  - six=1.11.0=py36_1
  - soupsieve=1.8=py36_0
  - sqlite=3.27.2=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - urllib3=1.24.1=py36_0
  - webencodings=0.5.1=py36_1
  - wheel=0.33.1=py36_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3

